// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyf36wva5CFexuXHNk8F1f3L0E80Zfyg0',
    appId: '1:490688055268:web:62bd75a3fa266642fa69f1',
    messagingSenderId: '490688055268',
    projectId: 'trackingsystem-8171f',
    authDomain: 'trackingsystem-8171f.firebaseapp.com',
    storageBucket: 'trackingsystem-8171f.appspot.com',
    measurementId: 'G-P6JWCWFG9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCydzoSClqy4RPmEDKQ05an0KtEM3lQTD0',
    appId: '1:490688055268:android:062e940d6cbb1b2cfa69f1',
    messagingSenderId: '490688055268',
    projectId: 'trackingsystem-8171f',
    storageBucket: 'trackingsystem-8171f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhRvzM8Pb7TQZ0U0F4JoCF50zrT7phbs',
    appId: '1:490688055268:ios:63b8d73ba308560afa69f1',
    messagingSenderId: '490688055268',
    projectId: 'trackingsystem-8171f',
    storageBucket: 'trackingsystem-8171f.appspot.com',
    iosClientId: '490688055268-o22a84p038sb587f0ibgttemmnpbnnpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingSystemDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKhRvzM8Pb7TQZ0U0F4JoCF50zrT7phbs',
    appId: '1:490688055268:ios:73be79fb7d9dfa9afa69f1',
    messagingSenderId: '490688055268',
    projectId: 'trackingsystem-8171f',
    storageBucket: 'trackingsystem-8171f.appspot.com',
    iosClientId: '490688055268-npge25cal7gml1v4r5t3qabt8b7m2heh.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingSystemDashboard.RunnerTests',
  );
}
